In [1]:
from x_utils import group_and_aggregate
import pandas as pd

In [2]:
# Charger les deux fichiers CSV
df_2009_2010 = pd.read_csv('data/silver_2009_2010_cleaned.csv')
df_2011 = pd.read_csv('data/silver_2011.csv')

In [3]:
df_2009_2010 = group_and_aggregate(df_2009_2010)

In [4]:
df_2009_2010[df_2009_2010['âˆƒ_items'] != df_2009_2010.Frequency]

,Recency,Frequency,Monetary,Quantity,Ã˜_Price,âˆƒ_items,%_Cancelled,Ã˜_Qty,Ã˜_InvoiceQty,Average_Price,Ã˜_basket,Country,Flag
Customer ID,,,,,,,,,,,,,
12346.0,725,14,51.76,54,10.498182,28,0.0,1.13,6.909091,12.07,45.00,United Kingdom,ðŸ‡¬ðŸ‡§
12347.0,403,2,1323.32,828,2.295070,70,0.0,13.36,426.042254,2.50,15.29,Iceland,ðŸ‡®ðŸ‡¸
12348.0,437,2,1114.96,1627,1.729459,21,0.0,53.22,777.783784,3.79,11.11,Finland,ðŸ‡«ðŸ‡®
12349.0,735,4,2646.99,988,8.406449,92,20.0,8.99,469.897196,8.36,-4.83,Italy,ðŸ‡®ðŸ‡¹
12352.0,392,2,343.80,188,3.033333,18,0.0,5.82,99.666667,20.05,23.96,Norway,ðŸ‡³ðŸ‡´
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18283.0,657,6,619.37,322,2.199401,158,0.0,1.79,67.147465,1.76,2.42,United Kingdom,ðŸ‡¬ðŸ‡§
18284.0,431,2,436.68,493,4.003103,28,0.0,17.00,476.931034,4.00,16.49,United Kingdom,ðŸ‡¬ðŸ‡§
18285.0,660,1,427.00,145,8.350000,12,0.0,12.08,145.000000,8.35,35.58,United Kingdom,ðŸ‡¬ðŸ‡§
18286.0,723,3,1188.43,592,4.379286,67,0.0,8.46,379.857143,4.38,27.23,United Kingdom,ðŸ‡¬ðŸ‡§
18287.0,737,5,2340.61,1425,2.841163,78,12.5,19.30,591.209302,2.24,-5.10,United Kingdom,ðŸ‡¬ðŸ‡§

In [5]:
df_2009_2010

,Recency,Frequency,Monetary,Quantity,Ã˜_Price,âˆƒ_items,%_Cancelled,Ã˜_Qty,Ã˜_InvoiceQty,Average_Price,Ã˜_basket,Country,Flag
Customer ID,,,,,,,,,,,,,
12346.0,725,14,51.76,54,10.498182,28,0.0,1.13,6.909091,12.07,45.00,United Kingdom,ðŸ‡¬ðŸ‡§
12347.0,403,2,1323.32,828,2.295070,70,0.0,13.36,426.042254,2.50,15.29,Iceland,ðŸ‡®ðŸ‡¸
12348.0,437,2,1114.96,1627,1.729459,21,0.0,53.22,777.783784,3.79,11.11,Finland,ðŸ‡«ðŸ‡®
12349.0,735,4,2646.99,988,8.406449,92,20.0,8.99,469.897196,8.36,-4.83,Italy,ðŸ‡®ðŸ‡¹
12352.0,392,2,343.80,188,3.033333,18,0.0,5.82,99.666667,20.05,23.96,Norway,ðŸ‡³ðŸ‡´
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18283.0,657,6,619.37,322,2.199401,158,0.0,1.79,67.147465,1.76,2.42,United Kingdom,ðŸ‡¬ðŸ‡§
18284.0,431,2,436.68,493,4.003103,28,0.0,17.00,476.931034,4.00,16.49,United Kingdom,ðŸ‡¬ðŸ‡§
18285.0,660,1,427.00,145,8.350000,12,0.0,12.08,145.000000,8.35,35.58,United Kingdom,ðŸ‡¬ðŸ‡§
18286.0,723,3,1188.43,592,4.379286,67,0.0,8.46,379.857143,4.38,27.23,United Kingdom,ðŸ‡¬ðŸ‡§
18287.0,737,5,2340.61,1425,2.841163,78,12.5,19.30,591.209302,2.24,-5.10,United Kingdom,ðŸ‡¬ðŸ‡§

In [6]:
df_2009_2010.to_csv('data/gold_2009_2010.csv', index=False)